/*! dsh-taskfold client bundle — GENERATED by scripts/build-client.mjs; do not edit.
    Single source of truth: plugins/task-stack-ui.mjs is spliced into the body. */
window.__ModuleLoader__.load({
	id: "dsh-taskfold-client",
	factory: (require) => {
		var module = { exports: {} };
		var exports = module.exports;
		Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
		let react = require("react");
		let primitives = require("@deepseek-ai/dsh-client-ui-primitives");
		//#region inlined: plugins/task-stack-ui.mjs (must stay import-free)
/**
 * taskStackUi — client-side presentation of the open-task stack.
 *
 * Reads the `taskMarks` session projection's wire view (host: task-marks.mjs /
 * compact-region.mjs; state = null | { pending, marks, pendingArchives? }).
 * marks are in STACK order: index 0 is the outermost (earliest-begun) task,
 * the last element is the innermost (currently active) task. tasks span turns
 * and survive host restarts, so this surface is session-global, unlike the
 * per-turn `todos` projection.
 *
 * Visual language is copied from the host's own list dock
 * (`dsh-client-ui-conversation`'s TodoPanel): the same composer-aligned card
 * geometry (--dsh-composer-* variables), the same .5px hairline + 12px radius
 * + `--dsw-specific-tip` surface, 13px rows, and a 16x16 glyph cell. Nothing
 * here can rely on shell CSS: plugin classes are NOT in the host stylesheet
 * (verified: 0 hits for first-party plugin classes in the shell bundles), so
 * this module ships and injects its own stylesheet — exactly what the
 * first-party bundles do (`style[data-plugin-css=...]`).
 *
 * Everything here is pure except makeTaskStack / injectTaskStackCss; the
 * react module is passed in so the file stays importable offline (node tests
 * without a browser) while the real bundle passes require('react').
 */

/**
 * Pure display model over the projection's wire state. Never throws on
 * foreign/malformed state (e.g. older persisted rows mid-replay): every field
 * is read defensively.
 * Returns {
 *   open: [{ seq, name, depth, innermost }],  // stack order, outermost first
 *   count,                                    // open.length
 *   innermost,                                // name of the active task or null
 *   pending: { begin, end },                  // lifecycle calls awaiting results
 *   closing: [{ seq, name }],                 // closed, fold queued (pendingArchives)
 *   empty,                                    // count === 0
 *   visible                                   // anything worth rendering at all
 * }
 */
function taskStackView(state) {
  const base = state !== null && typeof state === 'object' && !Array.isArray(state) ? state : null
  const marks = base !== null && Array.isArray(base.marks) ? base.marks : []
  const open = []
  for (let i = 0; i < marks.length; i += 1) {
    const m = marks[i]
    if (m === null || typeof m !== 'object' || typeof m.name !== 'string') continue
    open.push({
      seq: Number.isInteger(m.seq) ? m.seq : 0,
      name: m.name,
      depth: open.length + 1,
      innermost: false
    })
  }
  if (open.length > 0) open[open.length - 1].innermost = true
  let pending = { begin: 0, end: 0 }
  if (base !== null && base.pending !== null && typeof base.pending === 'object') {
    for (const key of Object.keys(base.pending)) {
      const e = base.pending[key]
      if (e === null || typeof e !== 'object') continue
      if (e.kind === 'begin') pending.begin += 1
      else if (e.kind === 'end') pending.end += 1
    }
  }
  const closing = []
  if (base !== null && Array.isArray(base.pendingArchives)) {
    for (const a of base.pendingArchives) {
      if (a !== null && typeof a === 'object' && typeof a.name === 'string') {
        closing.push({ seq: Number.isInteger(a.seq) ? a.seq : 0, name: a.name })
      }
    }
  }
  const pendingCount = pending.begin + pending.end
  return {
    open,
    count: open.length,
    innermost: open.length > 0 ? open[open.length - 1].name : null,
    pending,
    closing,
    empty: open.length === 0,
    visible: open.length > 0 || closing.length > 0 || pendingCount > 0
  }
}

/** Defensive accessor: any non-model input is treated as the empty model. */
function asModel(model) {
  return model !== null && typeof model === 'object' && Array.isArray(model.open)
    ? model
    : taskStackView(null)
}

/**
 * Count-only tail: 'folding' / 'pending' parts, used by the expanded header
 * and appended to the collapsed summary. '' when there is nothing extra.
 */
function tailSummary(model) {
  const m = asModel(model)
  const parts = []
  if (m.closing.length > 0) parts.push(m.closing.length + ' folding')
  const pending = m.pending.begin + m.pending.end
  if (pending > 0) parts.push(pending + ' pending')
  return parts.join(' · ')
}

/**
 * Expanded header meta: the stack at a glance, without repeating a task name
 * that is already listed below ('3 open · 1 folding').
 */
function countsSummary(model) {
  const m = asModel(model)
  const parts = []
  if (m.count > 0) parts.push(m.count + ' open')
  const tail = tailSummary(m)
  if (tail !== '') parts.push(tail)
  return parts.join(' · ')
}

/**
 * One-line summary for compact surfaces (tool row, collapsed subtitle) — the
 * analog of the todos projection's "N of M done": the active task name plus
 * the counts tail. '' when there is nothing worth printing.
 */
function planSummary(model) {
  const m = asModel(model)
  const tail = tailSummary(m)
  const suffix = tail === '' ? '' : ' · ' + tail
  if (m.count === 0) {
    if (m.pending.begin > 0) return 'opening a task…'
    if (m.pending.end > 0) return 'closing a task…'
    return ''
  }
  const head = m.count === 1 ? '1 open' : m.count + ' open'
  return head + ' · ' + m.innermost + suffix
}

/**
 * Session-projection key the client reads. Kept local so this module stays
 * import-free (the client bundle inlines it verbatim); the offline suite
 * asserts it equals task-marks.mjs' TASK_MARKS_KEY, which is what the host
 * actually registers.
 */
const TASK_STACK_KEY = 'taskMarks'

/** Identifier stamped on the injected <style>, mirroring the host bundles. */
const TASK_STACK_CSS_ID = 'dsh-taskfold/TaskStack.module.css'

/**
 * The dock's stylesheet. Geometry/typography are the host's list-dock recipe
 * (composer-aligned width, hairline border, 12px radius, 13px rows, 16x16
 * glyph cell); the rails/nodes are this widget's own. `var(..., fallback)`
 * is used for the composer variables, which the conversation package injects at
 * runtime — a missing variable must degrade to full width, never to a broken calc.
 */
function taskStackCss() {
  return [
    '.tf_root{box-sizing:border-box;',
    'width:calc(100% - 2*var(--dsh-composer-side-clearance,0px) - 4*var(--dsh-composer-dock-inset,0px));',
    'max-width:calc(var(--dsh-composer-card-max-width,100%) - 4*var(--dsh-composer-dock-inset,0px));',
    'border:.5px solid var(--dsw-alias-border-l1);',
    'background:var(--dsw-specific-tip);',
    'border-radius:12px;flex:none;margin:0 auto;overflow:hidden;',
    '--dsh-scrollbar-thumb:var(--dsw-alias-scrollbar-bg-l2);',
    '--dsh-scrollbar-thumb-hover:var(--dsw-alias-scrollbar-hover-l2)}',
    '.tf_body{display:flex;flex-direction:column;gap:6px;padding:6px 12px}',
    '.tf_header{display:flex;align-items:center;gap:10px;width:100%;padding:0;border:none;background:0 0;',
    'text-align:left;color:inherit;font:inherit;cursor:pointer}',
    '.tf_lead{display:grid;place-items:center;flex:none;color:var(--dsw-alias-label-tertiary)}',
    '.tf_title{flex:none;font-size:13px;font-weight:500;line-height:24px;color:var(--dsw-alias-label-primary)}',
    '.tf_meta{flex:auto;min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;',
    'font-size:13px;line-height:20px;color:var(--dsw-alias-label-tertiary)}',
    '.tf_chevron{display:grid;place-items:center;flex:none;color:var(--dsw-alias-label-tertiary);',
    'transition:transform var(--ds-transition-duration-fast,120ms) var(--ds-ease-in-out,ease)}',
    '.tf_chevronOpen{transform:rotate(180deg)}',
    '.tf_list{display:flex;flex-direction:column;gap:2px;margin:0;padding:0 0 2px;list-style:none;',
    'max-height:180px;overflow-y:auto}',
    '.tf_item{display:flex;align-items:center;min-width:0;border-radius:6px;',
    'font-size:13px;line-height:20px;color:var(--dsw-alias-label-secondary)}',
    '.tf_item:hover{background:var(--dsw-alias-interactive-bg-hover)}',
    '.tf_rail{display:flex;align-items:center;gap:0;flex:none;align-self:stretch}',
    '.tf_bar{flex:none;width:13px;height:100%;background:linear-gradient(',
    'to right,transparent 6px,var(--dsw-alias-border-l2) 6px,var(--dsw-alias-border-l2) 7px,transparent 7px)}',
    '.tf_node{flex:none;width:6px;height:6px;margin:0 7px 0 5px;border-radius:50%;',
    'background:var(--dsw-alias-label-caption)}',
    '.tf_nodeActive{background:var(--dsw-alias-state-business-primary)}',
    '.tf_nodeClosing{background:var(--dsw-alias-state-warn-primary)}',
    '.tf_name{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}',
    '.tf_nameActive{color:var(--dsw-alias-label-primary);font-weight:500}',
    '.tf_suffix{flex:none;margin-left:6px;color:var(--dsw-alias-label-caption)}'
  ].join('')
}

/**
 * Idempotently inject the stylesheet, the way every first-party bundle does:
 * keyed by `data-plugin-css` so a hot reload or remount never stacks copies.
 * Returns true when a tag was appended (false when already present or when
 * there is no document — e.g. the offline test renderer).
 */
function injectTaskStackCss(doc) {
  const d = doc !== undefined ? doc : (typeof document !== 'undefined' ? document : null)
  if (d === null || d === undefined || typeof d.createElement !== 'function') return false
  const head = d.head
  if (head === null || head === undefined || typeof head.appendChild !== 'function') return false
  if (typeof d.querySelector === 'function' && d.querySelector('style[data-plugin-css="' + TASK_STACK_CSS_ID + '"]') !== null) return false
  const tag = d.createElement('style')
  tag.dataset.plugin = 'dsh-taskfold'
  tag.dataset.pluginCss = TASK_STACK_CSS_ID
  tag.textContent = taskStackCss()
  head.appendChild(tag)
  return true
}

/** 14x14 stroke icons, in the host's icon idiom (currentColor, aria-hidden). */
function stackGlyph(h) {
  return h('svg', { width: 14, height: 14, viewBox: '0 0 14 14', fill: 'none', 'aria-hidden': 'true' },
    h('path', { d: 'M7 2.2 12.4 5 7 7.8 1.6 5z', stroke: 'currentColor', strokeWidth: 1.2, strokeLinejoin: 'round' }),
    h('path', { d: 'M2.6 8.3 7 10.7l4.4-2.4', stroke: 'currentColor', strokeWidth: 1.2, strokeLinecap: 'round', strokeLinejoin: 'round' }))
}

function chevronGlyph(h) {
  return h('svg', { width: 14, height: 14, viewBox: '0 0 14 14', fill: 'none', 'aria-hidden': 'true' },
    h('path', { d: 'M3.6 5.4 7 8.8l3.4-3.4', stroke: 'currentColor', strokeWidth: 1.4, strokeLinecap: 'round', strokeLinejoin: 'round' }))
}

/** Rails + state dot: depth is the leading rail run, state is the dot colour. */
function railCell(h, depth, state, key) {
  const bars = []
  for (let i = 1; i < depth; i += 1) bars.push(h('span', { key: 'b' + i, className: 'tf_bar' }))
  const node = state === 'active'
    ? 'tf_node tf_nodeActive'
    : state === 'closing' ? 'tf_node tf_nodeClosing' : 'tf_node'
  bars.push(h('span', { key: 'n', className: node }))
  return h('span', { key: key, className: 'tf_rail' }, bars)
}

/** One pending lifecycle intent: 'opening…' while a task_begin is in flight. */
function pendingRow(h, m) {
  const bits = []
  if (m.pending.begin > 0) bits.push('opening…')
  if (m.pending.end > 0) bits.push('closing…')
  return h('li', { key: 'pending', className: 'tf_item' },
    railCell(h, 1, 'pending', 'rail'),
    h('span', { className: 'tf_name' }, bits.join(' ')))
}

/**
 * Component factory. `react` is the react module (createElement + hooks of the
 * host's react instance). Renders the stack card; `compact` drops the per-task
 * list in favor of the one-line summary. Renders nothing at all when there is
 * no stack, no queued closure and no pending intent — the same "empty means
 * absent" rule the host's TodoPanel follows.
 */
function makeTaskStack(react) {
  const h = react.createElement
  const useState = react.useState

  function TaskStack({ model, compact, defaultCollapsed }) {
    const m = asModel(model)
    const [collapsed, setCollapsed] = useState(defaultCollapsed === true)
    if (!m.visible) return null
    const toggle = () => setCollapsed((v) => !v)
    const header = h('button', {
      type: 'button',
      className: 'tf_header',
      'aria-expanded': !collapsed,
      onClick: toggle
    },
    h('span', { className: 'tf_lead' }, stackGlyph(h)),
    h('span', { className: 'tf_title' }, 'tasks'),
    h('span', { className: 'tf_meta' }, compact === true || collapsed ? planSummary(m) : countsSummary(m)),
    h('span', { className: 'tf_chevron' + (collapsed ? '' : ' tf_chevronOpen') }, chevronGlyph(h)))

    if (compact === true) {
      return h('div', { className: 'tf_root tf_rootCompact' }, h('div', { className: 'tf_body' }, header))
    }
    const rows = []
    for (const t of m.open) {
      rows.push(h('li', {
        key: 'k' + t.seq + ':' + t.name,
        className: 'tf_item' + (t.innermost ? ' tf_itemActive' : '')
      },
      railCell(h, t.depth, t.innermost ? 'active' : 'open', 'rail'),
      h('span', { className: 'tf_name' + (t.innermost ? ' tf_nameActive' : '') }, t.name)))
    }
    for (const c of m.closing) {
      rows.push(h('li', { key: 'c' + c.seq + ':' + c.name, className: 'tf_item' },
        railCell(h, 1, 'closing', 'rail'),
        h('span', { className: 'tf_name' }, c.name),
        h('span', { className: 'tf_suffix' }, 'folding…')))
    }
    if (m.pending.begin + m.pending.end > 0) rows.push(pendingRow(h, m))
    return h('div', { className: 'tf_root' },
      h('div', { className: 'tf_body' },
        header,
        collapsed ? null : h('ul', { className: 'tf_list' }, rows)))
  }
  return TaskStack
}

/**
 * Dock adapter for the host's `conversation.input.dock` slot — the same
 * surface TodoDock uses for the `todos` projection. `useProjection` is a
 * host-provided render prop (dock components receive it from the chat package;
 * GoalDock and TodoDock consume the same prop). Read-only surface: the header
 * collapses/expands, nothing else is interactive.
 */
function makeTaskStackDock(react) {
  const h = react.createElement
  const TaskStack = makeTaskStack(react)
  function TaskStackDock({ useProjection, t }) {
    const state = typeof useProjection === 'function' ? useProjection(TASK_STACK_KEY) : undefined
    return h(TaskStack, { model: taskStackView(state) })
  }
  return TaskStackDock
}

		//#endregion
		//#region inlined: plugins/fold-settings-ui.mjs (must stay import-free)
/**
 * foldSettingsUi — the Settings-page card for the fold floor (client half).
 *
 * The host's Settings/Plugins page does NOT auto-render a plugin's exported
 * Config schema: `autoGenerate` is reserved for schema-driven clients and no
 * shipped client builds pages that way (dsh-settings README). Every visible
 * card is a browser-half component that binds its namespace through
 * `ctx.configForms` and registers into the Plugins page's `plugins.item`
 * slot — this module is taskfold's card for the `cmpct-region` namespace's
 * volatile `minSpanNodes` field (schema: compact-region.mjs Config export).
 *
 * Structure copies the official ui-settings-subagent companion: a
 * SettingsFormModel staging edits over the namespace, one SettingsValueField
 * control, one save/discard footer, and a `whileServed` registration so the
 * card appears exactly while the Host serves the namespace.
 *
 * Import-free by contract: react and the ui-primitives module arrive via the
 * makeFoldSettingsCard factory so this file stays loadable in node tests.
 * The client bundle build (scripts/build-client.mjs) inlines it beside
 * task-stack-ui.mjs.
 */

/** Namespace of this card's dictionary entries. */
const FOLD_SETTINGS_NS = 'settings.taskfold'
/** Host settings namespace this card edits — the profile entry id. */
const FOLD_SETTINGS_PLUGIN_NS = 'cmpct-region'
/** The one volatile field this card stages. */
const FOLD_SETTINGS_FIELD = 'minSpanNodes'
/** Inclusive bounds, mirroring the Config schema in compact-region.mjs. */
const FOLD_SETTINGS_MIN = 0
const FOLD_SETTINGS_MAX = 100000

/** English copy. */
const foldSettingsEn = {
  title: 'Taskfold',
  summary: 'Set the fold floor: how long a finished task must be before a summary is billed for it.',
  fieldLabel: 'Fold floor (messages + tool results)',
  helpLabel: 'About the fold floor',
  helpBody: 'A closed task folds into a summary only when its span covers at least this many surface nodes (messages + tool results). Shorter spans close unfolded — their original content stays on the surface, so no summarization call is billed. 0 folds everything.',
  overridden: 'Overridden',
  reset: 'Reset to default',
  invalid: 'Enter a whole number between 0 and 100000.',
  unavailable: 'This plugin is not loaded, so it cannot be configured right now.',
  readOnly: 'This deployment stores settings read-only.',
  saveFailed: 'The deployment did not accept these values; they were left for you to correct.',
  save: 'Save',
  saving: 'Saving…'
}

/** Simplified Chinese copy. */
const foldSettingsZh = {
  title: 'Taskfold',
  summary: '设置折叠下限：任务结束后至少多长才会为摘要计费。',
  fieldLabel: '折叠下限（消息 + 工具结果数）',
  helpLabel: '折叠下限说明',
  helpBody: '任务关闭后，只有其折叠区间覆盖的表面节点（消息 + 工具结果）不少于该数量时才会调用模型生成摘要；更短的区间直接关闭、不折叠，原始内容保留在表面上，不产生摘要计费。0 表示全部折叠。',
  overridden: '已覆盖',
  reset: '恢复默认',
  invalid: '请输入 0 到 100000 之间的整数。',
  unavailable: '该插件当前未加载，暂时无法配置。',
  readOnly: '本部署的设置为只读。',
  saveFailed: '本部署没有接受这些值，已保留供你修改。',
  save: '保存',
  saving: '保存中…'
}

/**
 * Wrap ui-primitives' whole-number field with the floor's inclusive bounds.
 * A draft that parses but falls outside 0..100000 is invalid (blocks save);
 * an empty draft still clears back to the composition default.
 * Pure — exported for offline tests.
 * @param {object} primitives - ui-primitives module (settingsNumberField).
 * @returns {object} field conversion spec for SettingsFormModel.
 */
function minSpanNodesFieldSpec(primitives) {
  const numeric = primitives.settingsNumberField(FOLD_SETTINGS_FIELD)
  return {
    ...numeric,
    parse: (text) => {
      const write = numeric.parse(text)
      if (write?.kind !== 'set') return write
      const value = write.value
      return Number.isSafeInteger(value) &&
        value >= FOLD_SETTINGS_MIN &&
        value <= FOLD_SETTINGS_MAX &&
        !Object.is(value, -0)
        ? write
        : undefined
    }
  }
}

/**
 * The labels the shared SettingsForm footer renders, from this card's copy.
 * @param {Function} t - this card's locale reader.
 * @returns {object} footer labels.
 */
function foldSettingsFormLabels(t) {
  return {
    unavailable: t('unavailable'),
    readOnly: t('readOnly'),
    saveFailed: t('saveFailed'),
    save: t('save'),
    saving: t('saving')
  }
}

/**
 * Build the card module: component + form factory + constants.
 * @param {object} react - the react module (createElement, Fragment).
 * @param {object} primitives - ui-primitives (SettingsForm, SettingsValueField, SettingsFormModel).
 * @returns {object} the pieces the client bundle wires together.
 */
function makeFoldSettingsCard(react, primitives) {
  const h = react.createElement
  const Fragment = react.Fragment

  /**
   * Stage one field over the `cmpct-region` namespace.
   * @param {object} scope - ctx.configForms.get('cmpct-region').
   * @returns {{ inject: () => object, dispose: () => void }} slot face + release.
   */
  function makeFoldSettingsForm(scope) {
    const form = new primitives.SettingsFormModel(scope, [minSpanNodesFieldSpec(primitives)])
    const store = form.bind(() => ({
      ...form.shell(),
      minSpanNodes: form.field(FOLD_SETTINGS_FIELD)
    }))
    return {
      inject() {
        return {
          hooks: { foldSettingsCard: store },
          ...form.actions()
        }
      },
      dispose() {
        form.dispose()
      }
    }
  }

  /**
   * The card: Plugins-page summary text, or the one-field form with footer.
   * Props arrive from the plugins.item slot: t, view, useFoldSettingsCard,
   * and the staged actions (edit/resetField/save/discard).
   */
  function FoldSettingsCard(props) {
    const t = props.t
    const state = props.useFoldSettingsCard((snapshot) => snapshot)
    if (props.view === 'summary') return t('summary')
    return h(
      primitives.SettingsForm,
      { labels: foldSettingsFormLabels(t), state, onSave: props.save, onDiscard: props.discard },
      h(primitives.SettingsValueField, {
        id: 'plugin-config-taskfold-min-span-nodes',
        label: t('fieldLabel'),
        help: {
          label: t('helpLabel'),
          content: h('p', null, t('helpBody'))
        },
        overriddenLabel: t('overridden'),
        resetLabel: t('reset'),
        invalidLabel: t('invalid'),
        numeric: true,
        disabled: !state.writable || state.saving,
        ...state.minSpanNodes,
        onEdit: (text) => { props.edit(FOLD_SETTINGS_FIELD, text) },
        onReset: () => { props.resetField(FOLD_SETTINGS_FIELD) }
      })
    )
  }

  return {
    FOLD_SETTINGS_NS,
    FOLD_SETTINGS_PLUGIN_NS,
    foldSettingsEn,
    foldSettingsZh,
    minSpanNodesFieldSpec,
    makeFoldSettingsForm,
    FoldSettingsCard
  }
}

		//#endregion
		const TaskStackDock = makeTaskStackDock(react);
		const FoldSettings = makeFoldSettingsCard(react, primitives);
		/** Required services: the host slot registry (minimal, like TodoDock).
		 * The settings card's services (locale, configForms) are injected as an
		 * OPTIONAL child fiber: a fiber pending on a missing service never
		 * fails, so the dock keeps working on deployments without ui-settings. */
		const inject = ["slots"];
		/** Mount the task-stack dock beside the shipped docks (todo:0 goal:10 queue:20). */
		function apply(ctx) {
			// Plugin CSS is not part of the shell stylesheet: every client bundle
			// injects its own, keyed by data-plugin-css (same as first-party ones).
			injectTaskStackCss();
			ctx.slots.inject("conversation.input.dock", () => ctx.slots.register({
				name: "conversation.input.dock",
				id: "task-stack",
				order: 15
			}, TaskStackDock));
			// Settings card for the fold floor: appears on the Plugins page while
			// the Host serves the cmpct-region namespace (schema-driven pages are
			// NOT auto-generated by any shipped client — each card registers itself).
			ctx.inject(["locale", "configForms"], (sctx) => {
				const t = sctx.locale.bind(FoldSettings.FOLD_SETTINGS_NS);
				sctx.effect(() => sctx.locale.register(FoldSettings.FOLD_SETTINGS_NS, {
					zh: FoldSettings.foldSettingsZh,
					en: FoldSettings.foldSettingsEn
				}), "taskfold: settings dictionaries");
				const form = FoldSettings.makeFoldSettingsForm(
					sctx.configForms.get(FoldSettings.FOLD_SETTINGS_PLUGIN_NS));
				sctx.effect(() => () => {
					form.dispose();
				}, "taskfold: settings form subscription");
				sctx.effect(() => sctx.configForms.whileServed(
					[FoldSettings.FOLD_SETTINGS_PLUGIN_NS],
					() => sctx.slots.inject("plugins.item", () => sctx.slots.register({
						name: "plugins.item",
						id: "taskfold",
						order: 40,
						label: () => t("title"),
						locale: FoldSettings.FOLD_SETTINGS_NS,
						inject: () => form.inject()
					}, FoldSettings.FoldSettingsCard))
				), "taskfold: settings card");
			});
		}
		exports.apply = apply;
		exports.inject = inject;
		return module.exports;
	}
});